[package]
name = "blust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
anyhow = "1.0.58"
pulldown-cmark = "0.9.2"
handlebars = "4.3.3"
serde_json = "1.0.82"
